/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar/SideBar.vue')['default']
    SideBarLink: typeof import('./src/components/SideBar/SideBarLink.vue')['default']
    Temperature: typeof import('./src/components/Temperature.vue')['default']
    Wind: typeof import('./src/components/Wind.vue')['default']
  }
}
